# Generated by Django 3.1.4 on 2020-12-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_property_response_exp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-project__dt_create', 'name'], 'verbose_name_plural': 'Properties'},
        ),
    ]
