# Generated by Django 3.1.4 on 2021-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201225_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='generatedQuestions',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Project Questions'),
        ),
    ]
