# Generated by Django 3.1.4 on 2021-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_generatedquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='generatedQuestionsLeadingText',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Project Questions Leading Text'),
        ),
    ]
