# Generated by Django 3.1.4 on 2021-01-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_activequestionindexlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='answerModifier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Answer Modifier Index List'),
        ),
        migrations.AddField(
            model_name='project',
            name='postQuestionMessage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Post Question Message Index List'),
        ),
    ]
