# Generated by Django 3.1.4 on 2021-01-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20210119_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='answerModifier',
            field=models.CharField(blank=True, default='{0: 1, 1: 1, 2: 1, 3: 1, 4: 1}', max_length=100, null=True, verbose_name='Answer Modifier Index List'),
        ),
        migrations.AlterField(
            model_name='project',
            name='postQuestionMessage',
            field=models.CharField(blank=True, default='{0: "", 1: "", 2: "", 3: "", 4: ""}', max_length=100, null=True, verbose_name='Post Question Message Index List'),
        ),
    ]
