# Generated by Django 3.1.4 on 2021-01-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20210119_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='postQuestionMessage',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Post Question Message Index List'),
        ),
    ]
