# Generated by Django 3.0.4 on 2020-12-10 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_auto_20201209_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.AddField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='doc_len',
            field=models.CharField(choices=[('PDS_1', '1 Page'), ('PDS_UPTO_5', 'Upto 5 Pages'), ('PDS_UPTO_20', 'Upto 20 Pages'), ('PDS_UNLIMITED', 'Unlimited')], default='PDS_1', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='doc_subtype',
            field=models.CharField(choices=[('PST_ASSESS', 'Assessment'), ('PST_REVIEW', 'Review'), ('PST_REPORT', 'Report'), ('PST_COMPAR', 'Comparison'), ('PST_POLICY_DOC', 'Policy Document'), ('PST_PROC_DOC', 'Procedures Document'), ('Creative Fiction', 'Creative Fiction'), ('Creative Non-Fiction', 'Creative Non-Fiction'), ('PST_DECIS_RATIO', 'Decision Rationale'), ('PST_SELECT_AN', 'Selection Analysis'), ('PST_RECOMM', 'Recommendation'), ('PST_EMAIL', 'Email'), ('PST_LETTER', 'Letter'), ('PST_MEMO', 'Memo'), ('PST_NOTICE', 'Notice'), ('PST_NEWSLETTER', 'Newsletter'), ('PST_ESSAY', 'Essay'), ('PST_ARTICLE', 'Article'), ('PST_BLOG_POST', 'Blog Post'), ('PST_EBOOK', 'E-Book'), ('PST_BOOK', 'Book'), ('PST_WHITEPPR', 'Whitepaper'), ('PST_WEBSITE', 'Website'), ('PST_LAND_PG', 'Landing Page'), ('PST_ADVERT', 'Advertisement'), ('PST_FLIER', 'Flier'), ('PST_BROCHURE', 'Brochure'), ('PST_PROPOS', 'Proposal'), ('PST_QUOTE', 'Quote'), ('PST_POT_SCEN', 'Potential Scenario'), ('PST_SCOPE', 'Scope'), ('PST_CHARTER', 'Charter'), ('PST_BUS_REQ_DOC', 'Business Requirements Document'), ('PST_STRAT', 'Strategy'), ('PST_PLAN', 'Plan'), ('PST_GOAL_OUT', 'Goal Outline'), ('PST_DEFIN_DOC', 'Definition Document'), ('PST_HOW_ART', 'How-To Article'), ('PST_PAT_SPEC', 'Patent Specification'), ('PST_PROD_MAN', 'Product Manual'), ('PST_CURRIC', 'Curriculum'), ('PST_TRAIN_DOC', 'Training Document')], default='PST_ASSESS', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='doc_topic',
            field=models.CharField(choices=[('PTOP_1', 'Person'), ('PTOP_2', 'Company'), ('PTOP_3', 'Group'), ('PTOP_4', 'Product or Service'), ('PTOP_5', 'Concept or Thing'), ('PTOP_6', 'Place, Destination or Building')], default='PTOP_1', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='doc_type',
            field=models.CharField(choices=[('PT_AN_REP', 'Analysis Report'), ('PT_COMP_DOC', 'Compliance Document'), ('PT_CREAT_CONT', 'Creative Content'), ('PT_RATIONALE', 'Rationale'), ('PT_DIR_COMM', 'Direct Communication'), ('PT_PERS_PEICE', 'Persuasive Piece'), ('PT_PROMO_CONT', 'Promotional Content'), ('PT_BUSIN_PROP', 'Business Proposal'), ('PT_REQ_DOC', 'Requirements Document'), ('PT_FUT_SCEN', 'Future Scenario'), ('PT_TECH_DOC', 'Technical Document'), ('PT_TRAIN_PROG', 'Training Program')], default='PT_AN_REP', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('STARTED', 'Just Started'), ('INIT_QUESTIONS', 'Asking Initial Questions'), ('BASECAMP', 'Reached Document Basecamp')], default='STARTED', max_length=25),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETE', 'Complete')], default='IN_PROGRESS', max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=25)),
                ('p_response', models.CharField(max_length=1000, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='props', to='projects.Project')),
            ],
            options={
                'ordering': ['project__title', 'p_name'],
            },
        ),
    ]
