# Generated by Django 3.1.4 on 2020-12-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='response_exp',
            field=models.CharField(max_length=1100, null=True),
        ),
    ]
