# Generated by Django 3.0.4 on 2020-12-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20201210_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='doc_len',
            field=models.CharField(choices=[('PDS_1', '1 Page'), ('PDS_UPTO_5', 'Upto 5 Pages'), ('PDS_UPTO_20', 'Upto 20 Pages'), ('PDS_UNLIMITED', 'Unlimited')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='doc_subtype',
            field=models.CharField(choices=[('PST_ASSESS', 'Assessment'), ('PST_REVIEW', 'Review'), ('PST_REPORT', 'Report'), ('PST_COMPAR', 'Comparison'), ('PST_POLICY_DOC', 'Policy Document'), ('PST_PROC_DOC', 'Procedures Document'), ('Creative Fiction', 'Creative Fiction'), ('Creative Non-Fiction', 'Creative Non-Fiction'), ('PST_DECIS_RATIO', 'Decision Rationale'), ('PST_SELECT_AN', 'Selection Analysis'), ('PST_RECOMM', 'Recommendation'), ('PST_EMAIL', 'Email'), ('PST_LETTER', 'Letter'), ('PST_MEMO', 'Memo'), ('PST_NOTICE', 'Notice'), ('PST_NEWSLETTER', 'Newsletter'), ('PST_ESSAY', 'Essay'), ('PST_ARTICLE', 'Article'), ('PST_BLOG_POST', 'Blog Post'), ('PST_EBOOK', 'E-Book'), ('PST_BOOK', 'Book'), ('PST_WHITEPPR', 'Whitepaper'), ('PST_WEBSITE', 'Website'), ('PST_LAND_PG', 'Landing Page'), ('PST_ADVERT', 'Advertisement'), ('PST_FLIER', 'Flier'), ('PST_BROCHURE', 'Brochure'), ('PST_PROPOS', 'Proposal'), ('PST_QUOTE', 'Quote'), ('PST_POT_SCEN', 'Potential Scenario'), ('PST_SCOPE', 'Scope'), ('PST_CHARTER', 'Charter'), ('PST_BUS_REQ_DOC', 'Business Requirements Document'), ('PST_STRAT', 'Strategy'), ('PST_PLAN', 'Plan'), ('PST_GOAL_OUT', 'Goal Outline'), ('PST_DEFIN_DOC', 'Definition Document'), ('PST_HOW_ART', 'How-To Article'), ('PST_PAT_SPEC', 'Patent Specification'), ('PST_PROD_MAN', 'Product Manual'), ('PST_CURRIC', 'Curriculum'), ('PST_TRAIN_DOC', 'Training Document')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='doc_topic',
            field=models.CharField(choices=[('PTOP_1', 'Person'), ('PTOP_2', 'Company'), ('PTOP_3', 'Group'), ('PTOP_4', 'Product or Service'), ('PTOP_5', 'Concept or Thing'), ('PTOP_6', 'Place, Destination or Building')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='doc_type',
            field=models.CharField(choices=[('PT_AN_REP', 'Analysis Report'), ('PT_COMP_DOC', 'Compliance Document'), ('PT_CREAT_CONT', 'Creative Content'), ('PT_RATIONALE', 'Rationale'), ('PT_DIR_COMM', 'Direct Communication'), ('PT_PERS_PEICE', 'Persuasive Piece'), ('PT_PROMO_CONT', 'Promotional Content'), ('PT_BUSIN_PROP', 'Business Proposal'), ('PT_REQ_DOC', 'Requirements Document'), ('PT_FUT_SCEN', 'Future Scenario'), ('PT_TECH_DOC', 'Technical Document'), ('PT_TRAIN_PROG', 'Training Program')], max_length=25, null=True),
        ),
    ]
