# Generated by Django 3.0.4 on 2020-12-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20201210_1720'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['project__title', 'name']},
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='p_response',
            new_name='response',
        ),
    ]
