# Project 'stage' options
PROJ_STAGE_STARTED = 'STARTED'                              # just started, subtye selection pending
PROJ_STAGE_INIT_QUESTIONS = 'INIT_QUESTIONS'                # in process of asking initial set of questions
PROJ_STAGE_BASECAMP = 'BASECAMP'                            # reached document basecamp stage

PROJ_STAGE_DEFAULT = PROJ_STAGE_STARTED                     # default project stage on creation

PROJ_TEXT_STAGE_STARTED = 'Just Started'
PROJ_TEXT_STAGE_INIT_QUESTIONS = 'Asking Initial Questions'
PROJ_TEXT_STAGE_BASECAMP = 'Reached Document Basecamp'

PROJ_STAGE_CHOICES = [
    (PROJ_STAGE_STARTED, PROJ_TEXT_STAGE_STARTED),
    (PROJ_STAGE_INIT_QUESTIONS, PROJ_TEXT_STAGE_INIT_QUESTIONS),
    (PROJ_STAGE_BASECAMP, PROJ_TEXT_STAGE_BASECAMP),
]


# Project 'status' options
PROJ_STATUS_IN_PROGRESS = 'IN_PROGRESS'                     # project in-progress
PROJ_STATUS_COMPLETE = 'COMPLETE'                           # project complete

PROJ_STATUS_DEFAULT = PROJ_STATUS_IN_PROGRESS               # default project status on creation

PROJ_TEXT_STATUS_IN_PROGRESS = 'In Progress'
PROJ_TEXT_STATUS_COMPLETE = 'Complete'

PROJ_STATUS_CHOICES = [
    (PROJ_STATUS_IN_PROGRESS, PROJ_TEXT_STATUS_IN_PROGRESS),
    (PROJ_STATUS_COMPLETE, PROJ_TEXT_STATUS_COMPLETE),
]

# Project 'doc_type' options
PROJ_TYPE_ANALYSIS_REPORT = 'PT_AN_REP'
PROJ_TYPE_COMPLIANCE_DOCUMENT = 'PT_COMP_DOC'
PROJ_TYPE_CREATIVE_CONTENT = 'PT_CREAT_CONT'
PROJ_TYPE_RATIONALE = 'PT_RATIONALE'
PROJ_TYPE_DIRECT_COMMUNICATION = 'PT_DIR_COMM'
PROJ_TYPE_PERSUASIVE_PIECE = 'PT_PERS_PEICE'
PROJ_TYPE_PROMOTIONAL_CONTENT = 'PT_PROMO_CONT'
PROJ_TYPE_BUSINESS_PROPOSAL = 'PT_BUSIN_PROP'
PROJ_TYPE_REQUIREMENTS_DOCUMENT = 'PT_REQ_DOC'
PROJ_TYPE_FUTURE_SCENARIO = 'PT_FUT_SCEN'
PROJ_TYPE_TECHNICAL_DOCUMENT = 'PT_TECH_DOC'
PROJ_TYPE_TRAINING_PROGRAM = 'PT_TRAIN_PROG'

PROJ_TEXT_TYPE_ANALYSIS_REPORT = 'Analysis Report'
PROJ_TEXT_TYPE_COMPLIANCE_DOCUMENT = 'Compliance Document'
PROJ_TEXT_TYPE_CREATIVE_CONTENT = 'Creative Content'
PROJ_TEXT_TYPE_RATIONALE = 'Rationale'
PROJ_TEXT_TYPE_DIRECT_COMMUNICATION = 'Direct Communication'
PROJ_TEXT_TYPE_PERSUASIVE_PIECE = 'Persuasive Piece'
PROJ_TEXT_TYPE_PROMOTIONAL_CONTENT = 'Promotional Content'
PROJ_TEXT_TYPE_BUSINESS_PROPOSAL = 'Business Proposal'
PROJ_TEXT_TYPE_REQUIREMENTS_DOCUMENT = 'Requirements Document'
PROJ_TEXT_TYPE_FUTURE_SCENARIO = 'Future Scenario'
PROJ_TEXT_TYPE_TECHNICAL_DOCUMENT = 'Technical Document'
PROJ_TEXT_TYPE_TRAINING_PROGRAM = 'Training Program'

PROJ_TYPE_CHOICES = [
    (PROJ_TYPE_ANALYSIS_REPORT, PROJ_TEXT_TYPE_ANALYSIS_REPORT), 
    (PROJ_TYPE_COMPLIANCE_DOCUMENT, PROJ_TEXT_TYPE_COMPLIANCE_DOCUMENT),
    (PROJ_TYPE_CREATIVE_CONTENT, PROJ_TEXT_TYPE_CREATIVE_CONTENT), 
    (PROJ_TYPE_RATIONALE, PROJ_TEXT_TYPE_RATIONALE), 
    (PROJ_TYPE_DIRECT_COMMUNICATION, PROJ_TEXT_TYPE_DIRECT_COMMUNICATION),
    (PROJ_TYPE_PERSUASIVE_PIECE, PROJ_TEXT_TYPE_PERSUASIVE_PIECE ), 
    (PROJ_TYPE_PROMOTIONAL_CONTENT, PROJ_TEXT_TYPE_PROMOTIONAL_CONTENT), 
    (PROJ_TYPE_BUSINESS_PROPOSAL, PROJ_TEXT_TYPE_BUSINESS_PROPOSAL),
    (PROJ_TYPE_REQUIREMENTS_DOCUMENT, PROJ_TEXT_TYPE_REQUIREMENTS_DOCUMENT), 
    (PROJ_TYPE_FUTURE_SCENARIO, PROJ_TEXT_TYPE_FUTURE_SCENARIO), 
    (PROJ_TYPE_TECHNICAL_DOCUMENT, PROJ_TEXT_TYPE_TECHNICAL_DOCUMENT),
    (PROJ_TYPE_TRAINING_PROGRAM, PROJ_TEXT_TYPE_TRAINING_PROGRAM),
]

# Project 'subtype' options

PROJ_SUBTYPE_ASSESSMENT = 'PST_'
PROJ_SUBTYPE_REVIEW = 'PST_'
PROJ_SUBTYPE_REPORT = 'PST_'
PROJ_SUBTYPE_COMPARISON = 'PST_'

PROJ_SUBTYPE_POLICY_DOCUMENT = 'PST_'
PROJ_SUBTYPE_PROCEDURES_DOCUMENT = 'PST_'

PROJ_SUBTYPE_CREATIVE_FICTION = 'PST_'
PROJ_SUBTYPE_CREATION_NON_FICTION = 'PST_'

PROJ_SUBTYPE_DECISION_RATIONALE = 'PST_'
PROJ_SUBTYPE_SELECTION_ANALYSIS = 'PST_'
PROJ_SUBTYPE_RECOMMENDATION = 'PST_'

PROJ_SUBTYPE_EMAIL = 'PST_'
PROJ_SUBTYPE_LETTER = 'PST_'
PROJ_SUBTYPE_MEMO = 'PST_'
PROJ_SUBTYPE_NOTICE = 'PST_'
PROJ_SUBTYPE_NEWSLETTER = 'PST_'

PROJ_SUBTYPE_ESSAY = 'PST_'
PROJ_SUBTYPE_ARTICLE = 'PST_'
PROJ_SUBTYPE_BLOG_POST = 'PST_'
PROJ_SUBTYPE_E_BOOK = 'PST_'
PROJ_SUBTYPE_BOOK = 'PST_'
PROJ_SUBTYPE_WHITEPAPER = 'PST_'

PROJ_SUBTYPE_WEBSITE = 'PST_'
PROJ_SUBTYPE_LANDING_PAGE = 'PST_'
PROJ_SUBTYPE_ADVERTISEMENT = 'PST_'
PROJ_SUBTYPE_FLIER = 'PST_'
PROJ_SUBTYPE_BROCHURE = 'PST_'

PROJ_SUBTYPE_PROPOSAL = 'PST_'
PROJ_SUBTYPE_QUOTE = 'PST_'
PROJ_SUBTYPE_POTENTIAL_SCENARIO = 'PST_'

PROJ_SUBTYPE_SCOPE = 'PST_'
PROJ_SUBTYPE_CHARTER = 'PST_'
PROJ_SUBTYPE_BUSINESS_REQUIREMENTS_DOCUMENT = 'PST_'

PROJ_SUBTYPE_STRATEGY = 'PST_'
PROJ_SUBTYPE_PLAN = 'PST_'
PROJ_SUBTYPE_GOAL_OUTLINE = 'PST_'
PROJ_SUBTYPE_DEFINITION_DOCUMENT = 'PST_'

PROJ_SUBTYPE_HOW_TO_ARTICLE = 'PST_'
PROJ_SUBTYPE_PATENT_SPECIFICATION = 'PST_'
PROJ_SUBTYPE_PRODUCT_MANUAL = 'PST_'

PROJ_SUBTYPE_CURRICULUM = 'PST_'
PROJ_SUBTYPE_TRAINING_DOCUMENT = 'PST_'


PROJ_TEXT_SUBTYPE_ASSESSMENT = 'Assessment'
PROJ_TEXT_SUBTYPE_REVIEW = 'Review'
PROJ_TEXT_SUBTYPE_REPORT = 'Report'
PROJ_TEXT_SUBTYPE_COMPARISON = 'Comparison'

PROJ_TEXT_SUBTYPE_POLICY_DOCUMENT = 'Policy Document'
PROJ_TEXT_SUBTYPE_PROCEDURES_DOCUMENT = 'Procedures Document'

PROJ_SUBTYPE_CREATIVE_FICTION = 'Creative Fiction'
PROJ_SUBTYPE_CREATION_NON_FICTION = 'Creative Non-Fiction'

PROJ_TEXT_SUBTYPE_DECISION_RATIONALE = 'Decision Rationale'
PROJ_TEXT_SUBTYPE_SELECTION_ANALYSIS = 'Selection Analysis'
PROJ_TEXT_SUBTYPE_RECOMMENDATION = 'Recommendation'

PROJ_TEXT_SUBTYPE_EMAIL = 'Email'
PROJ_TEXT_SUBTYPE_LETTER = 'Letter'
PROJ_TEXT_SUBTYPE_MEMO = 'Memo'
PROJ_TEXT_SUBTYPE_NOTICE = 'Notice'
PROJ_TEXT_SUBTYPE_NEWSLETTER = 'Newsletter'

PROJ_TEXT_SUBTYPE_ESSAY = 'Essay'
PROJ_TEXT_SUBTYPE_ARTICLE = 'Article'
PROJ_TEXT_SUBTYPE_BLOG_POST = 'Blog Post'
PROJ_TEXT_SUBTYPE_E_BOOK = 'E-Book'
PROJ_TEXT_SUBTYPE_BOOK = 'Book'
PROJ_TEXT_SUBTYPE_WHITEPAPER = 'Whitepaper'

PROJ_TEXT_SUBTYPE_WEBSITE = 'Website'
PROJ_TEXT_SUBTYPE_LANDING_PAGE = 'Landing Page'
PROJ_TEXT_SUBTYPE_ADVERTISEMENT = 'Advertisement'
PROJ_TEXT_SUBTYPE_FLIER = 'Flier'
PROJ_TEXT_SUBTYPE_BROCHURE = 'Brochure'

PROJ_TEXT_SUBTYPE_PROPOSAL = 'Proposal'
PROJ_TEXT_SUBTYPE_QUOTE = 'Quote'
PROJ_TEXT_SUBTYPE_POTENTIAL_SCENARIO = 'Potential Scenario'

PROJ_TEXT_SUBTYPE_SCOPE = 'Scope'
PROJ_TEXT_SUBTYPE_CHARTER = 'Charter'
PROJ_TEXT_SUBTYPE_BUSINESS_REQUIREMENTS_DOCUMENT = 'Business Requirements Document'

PROJ_TEXT_SUBTYPE_STRATEGY = 'Strategy'
PROJ_TEXT_SUBTYPE_PLAN = 'Plan'
PROJ_TEXT_SUBTYPE_GOAL_OUTLINE = 'Goal Outline'
PROJ_TEXT_SUBTYPE_DEFINITION_DOCUMENT = 'Definition Document'

PROJ_TEXT_SUBTYPE_HOW_TO_ARTICLE = 'How-To Article'
PROJ_TEXT_SUBTYPE_PATENT_SPECIFICATION = 'Patent Specification'
PROJ_TEXT_SUBTYPE_PRODUCT_MANUAL = 'Product Manual'

PROJ_TEXT_SUBTYPE_CURRICULUM = 'Curriculum'
PROJ_TEXT_SUBTYPE_TRAINING_DOCUMENT = 'Training Document'

doc_list2 = ['Available types...',
             ['assessment', 'review', 'report', 'comparison'],
             ['policy document', 'proceedures document'],
             ['creative fiction', 'creative non-fiction'],
             ['decision rationale', 'selection analysis', 'recommendation'],
             ['email', 'letter', 'memo', 'notice', 'newsletter'],
             ['essay', 'article', 'blog post', 'e-book', 'book', 'whitepaper'],
             ['website', 'landing page', 'advertisement', 'flier', 'brochure'],
             ['proposal', 'quote', 'potential scenario'],
             ['scope', 'charter', 'business requirements document'],
             ['strategy', 'plan', 'goal outline','definition document'],
             ['how to article', 'patent specification', 'product manual'],
             ['curriculum', 'training document']]

PROJ_SUBTYPE_CHOICES = [
    (PROJ_SUBTYPE_ASSESSMENT, PROJ_TEXT_SUBTYPE_ASSESSMENT),
    (PROJ_SUBTYPE_REVIEW, PROJ_TEXT_SUBTYPE_REVIEW),
    (PROJ_SUBTYPE_REPORT, PROJ_TEXT_SUBTYPE_REPORT),
    (PROJ_SUBTYPE_COMPARISON, PROJ_TEXT_SUBTYPE_COMPARISON),

    (PROJ_SUBTYPE_POLICY_DOCUMENT, PROJ_TEXT_SUBTYPE_POLICY_DOCUMENT),
    (PROJ_SUBTYPE_PROCEDURES_DOCUMENT, PROJ_TEXT_SUBTYPE_PROCEDURES_DOCUMENT),

    (PROJ_SUBTYPE_CREATIVE_FICTION, PROJ_SUBTYPE_CREATIVE_FICTION),
    (PROJ_SUBTYPE_CREATION_NON_FICTION, PROJ_SUBTYPE_CREATION_NON_FICTION),

    (PROJ_SUBTYPE_DECISION_RATIONALE, PROJ_TEXT_SUBTYPE_DECISION_RATIONALE),
    (PROJ_SUBTYPE_SELECTION_ANALYSIS, PROJ_TEXT_SUBTYPE_SELECTION_ANALYSIS),
    (PROJ_SUBTYPE_RECOMMENDATION, PROJ_TEXT_SUBTYPE_RECOMMENDATION),

    (PROJ_SUBTYPE_EMAIL, PROJ_TEXT_SUBTYPE_EMAIL),
    (PROJ_SUBTYPE_LETTER, PROJ_TEXT_SUBTYPE_LETTER),
    (PROJ_SUBTYPE_MEMO, PROJ_TEXT_SUBTYPE_MEMO),
    (PROJ_SUBTYPE_NOTICE, PROJ_TEXT_SUBTYPE_NOTICE),
    (PROJ_SUBTYPE_NEWSLETTER, PROJ_TEXT_SUBTYPE_NEWSLETTER),

    (PROJ_SUBTYPE_ESSAY, PROJ_TEXT_SUBTYPE_ESSAY),
    (PROJ_SUBTYPE_ARTICLE, PROJ_TEXT_SUBTYPE_ARTICLE),
    (PROJ_SUBTYPE_BLOG_POST, PROJ_TEXT_SUBTYPE_BLOG_POST),
    (PROJ_SUBTYPE_E_BOOK, PROJ_TEXT_SUBTYPE_E_BOOK),
    (PROJ_SUBTYPE_BOOK, PROJ_TEXT_SUBTYPE_BOOK),
    (PROJ_SUBTYPE_WHITEPAPER, PROJ_TEXT_SUBTYPE_WHITEPAPER),

    (PROJ_SUBTYPE_WEBSITE, PROJ_TEXT_SUBTYPE_WEBSITE),
    (PROJ_SUBTYPE_LANDING_PAGE, PROJ_TEXT_SUBTYPE_LANDING_PAGE),
    (PROJ_SUBTYPE_ADVERTISEMENT, PROJ_TEXT_SUBTYPE_ADVERTISEMENT),
    (PROJ_SUBTYPE_FLIER, PROJ_TEXT_SUBTYPE_FLIER),
    (PROJ_SUBTYPE_BROCHURE, PROJ_TEXT_SUBTYPE_BROCHURE),

    (PROJ_SUBTYPE_PROPOSAL, PROJ_TEXT_SUBTYPE_PROPOSAL),
    (PROJ_SUBTYPE_QUOTE, PROJ_TEXT_SUBTYPE_QUOTE),
    (PROJ_SUBTYPE_POTENTIAL_SCENARIO, PROJ_TEXT_SUBTYPE_POTENTIAL_SCENARIO),

    (PROJ_SUBTYPE_SCOPE, PROJ_TEXT_SUBTYPE_SCOPE),
    (PROJ_SUBTYPE_CHARTER, PROJ_TEXT_SUBTYPE_CHARTER),
    (PROJ_SUBTYPE_BUSINESS_REQUIREMENTS_DOCUMENT, PROJ_TEXT_SUBTYPE_BUSINESS_REQUIREMENTS_DOCUMENT),
    
    (PROJ_SUBTYPE_STRATEGY, PROJ_TEXT_SUBTYPE_STRATEGY),
    (PROJ_SUBTYPE_PLAN, PROJ_TEXT_SUBTYPE_PLAN),
    (PROJ_SUBTYPE_GOAL_OUTLINE, PROJ_TEXT_SUBTYPE_GOAL_OUTLINE),
    (PROJ_SUBTYPE_DEFINITION_DOCUMENT, PROJ_TEXT_SUBTYPE_DEFINITION_DOCUMENT),

    (PROJ_SUBTYPE_HOW_TO_ARTICLE, PROJ_TEXT_SUBTYPE_HOW_TO_ARTICLE),
    (PROJ_SUBTYPE_PATENT_SPECIFICATION, PROJ_TEXT_SUBTYPE_PATENT_SPECIFICATION),
    (PROJ_SUBTYPE_PRODUCT_MANUAL, PROJ_TEXT_SUBTYPE_PRODUCT_MANUAL),

    (PROJ_SUBTYPE_CURRICULUM, PROJ_TEXT_SUBTYPE_CURRICULUM),
    (PROJ_SUBTYPE_TRAINING_DOCUMENT, PROJ_TEXT_SUBTYPE_TRAINING_DOCUMENT),
]

PROJ_SUBTYPE_CHOICES_SEL = {
    PROJ_TYPE_ANALYSIS_REPORT: [
        (PROJ_SUBTYPE_ASSESSMENT, PROJ_TEXT_SUBTYPE_ASSESSMENT),
        (PROJ_SUBTYPE_REVIEW, PROJ_TEXT_SUBTYPE_REVIEW),
        (PROJ_SUBTYPE_REPORT, PROJ_TEXT_SUBTYPE_REPORT),
        (PROJ_SUBTYPE_COMPARISON, PROJ_TEXT_SUBTYPE_COMPARISON),
    ], 
    PROJ_TYPE_COMPLIANCE_DOCUMENT: [
        (PROJ_SUBTYPE_POLICY_DOCUMENT, PROJ_TEXT_SUBTYPE_POLICY_DOCUMENT),
        (PROJ_SUBTYPE_PROCEDURES_DOCUMENT, PROJ_TEXT_SUBTYPE_PROCEDURES_DOCUMENT),
    ],
    PROJ_TYPE_CREATIVE_CONTENT: [
        (PROJ_SUBTYPE_CREATIVE_FICTION, PROJ_SUBTYPE_CREATIVE_FICTION),
        (PROJ_SUBTYPE_CREATION_NON_FICTION, PROJ_SUBTYPE_CREATION_NON_FICTION),
    ], 
    PROJ_TYPE_RATIONALE: [
        (PROJ_SUBTYPE_DECISION_RATIONALE, PROJ_TEXT_SUBTYPE_DECISION_RATIONALE),
        (PROJ_SUBTYPE_SELECTION_ANALYSIS, PROJ_TEXT_SUBTYPE_SELECTION_ANALYSIS),
        (PROJ_SUBTYPE_RECOMMENDATION, PROJ_TEXT_SUBTYPE_RECOMMENDATION),
    ], 
    PROJ_TYPE_DIRECT_COMMUNICATION: [
        (PROJ_SUBTYPE_EMAIL, PROJ_TEXT_SUBTYPE_EMAIL),
        (PROJ_SUBTYPE_LETTER, PROJ_TEXT_SUBTYPE_LETTER),
        (PROJ_SUBTYPE_MEMO, PROJ_TEXT_SUBTYPE_MEMO),
        (PROJ_SUBTYPE_NOTICE, PROJ_TEXT_SUBTYPE_NOTICE),
        (PROJ_SUBTYPE_NEWSLETTER, PROJ_TEXT_SUBTYPE_NEWSLETTER),
    ],
    PROJ_TYPE_PERSUASIVE_PIECE: [
        (PROJ_SUBTYPE_ESSAY, PROJ_TEXT_SUBTYPE_ESSAY),
        (PROJ_SUBTYPE_ARTICLE, PROJ_TEXT_SUBTYPE_ARTICLE),
        (PROJ_SUBTYPE_BLOG_POST, PROJ_TEXT_SUBTYPE_BLOG_POST),
        (PROJ_SUBTYPE_E_BOOK, PROJ_TEXT_SUBTYPE_E_BOOK),
        (PROJ_SUBTYPE_BOOK, PROJ_TEXT_SUBTYPE_BOOK),
        (PROJ_SUBTYPE_WHITEPAPER, PROJ_TEXT_SUBTYPE_WHITEPAPER),
    ], 
    PROJ_TYPE_PROMOTIONAL_CONTENT: [
        (PROJ_SUBTYPE_WEBSITE, PROJ_TEXT_SUBTYPE_WEBSITE),
        (PROJ_SUBTYPE_LANDING_PAGE, PROJ_TEXT_SUBTYPE_LANDING_PAGE),
        (PROJ_SUBTYPE_ADVERTISEMENT, PROJ_TEXT_SUBTYPE_ADVERTISEMENT),
        (PROJ_SUBTYPE_FLIER, PROJ_TEXT_SUBTYPE_FLIER),
        (PROJ_SUBTYPE_BROCHURE, PROJ_TEXT_SUBTYPE_BROCHURE),
    ], 
    PROJ_TYPE_BUSINESS_PROPOSAL: [
        (PROJ_SUBTYPE_PROPOSAL, PROJ_TEXT_SUBTYPE_PROPOSAL),
        (PROJ_SUBTYPE_QUOTE, PROJ_TEXT_SUBTYPE_QUOTE),
        (PROJ_SUBTYPE_POTENTIAL_SCENARIO, PROJ_TEXT_SUBTYPE_POTENTIAL_SCENARIO),
    ],
    PROJ_TYPE_REQUIREMENTS_DOCUMENT: [

    ], 
    PROJ_TYPE_FUTURE_SCENARIO: [
        (PROJ_SUBTYPE_STRATEGY, PROJ_TEXT_SUBTYPE_STRATEGY),
        (PROJ_SUBTYPE_PLAN, PROJ_TEXT_SUBTYPE_PLAN),
        (PROJ_SUBTYPE_GOAL_OUTLINE, PROJ_TEXT_SUBTYPE_GOAL_OUTLINE),
        (PROJ_SUBTYPE_DEFINITION_DOCUMENT, PROJ_TEXT_SUBTYPE_DEFINITION_DOCUMENT),
    ], 
    PROJ_TYPE_TECHNICAL_DOCUMENT: [

    ],
    PROJ_TYPE_TRAINING_PROGRAM: [

    ],
}
    