#list places or terms requiring "The" that don't conform to rules for topic expression
the_singular = ['Thames', 'data']

the_list = ['sea', 'river', 'rivers', 'ocean', 'oceans', 'council',
            'councils']

the_words = ['Bahamas',
             'Cayman Islands',
             'Central African Republic',
             'Channel Islands',
             'Comoros',
             'Columbia',
             'Czech Republic',
             'Dominican Republic',
             'Equator'
             'Falkland Islands',
             'Gambia',
             'Isle of Man',
             'Ivory Coast',
             'Leeward Islands',
             'Maldives',
             'Maldive Islands',
             'Marshall Islands',
             'Netherlands',
             'Netherlands Antilles',
             'Northern Hemisphere',
             'Philippines',
             'Solomon Islands',
             'Southern Hemisphere',
             'Turks and Caicos Islands',
             'United Arab Emirates',
             'United Kingdom',
             'United Kingdom of Great Britain and Nothern Ireland',
             'United States of America',
             'Virgin Islands',
             'United States',
             'USA',
             'UK',
             'EU',
             'Eurpoean Union',
             'Cocos Islands',
             'Amazon',
             'Danube',
             'Don',
             'Euphrates',
             'Ganges',
             'Huang',
             'Hudson',
             'Indus',
             'Mackenzie',
             'Mekong',
             'Mississippi',
             'Missouri',
             'Nile',
             'Ob',
             'Ohio',
             'Orinoco',
             'Po',
             'Rhine',
             'Rhone',
             'Rio Grande',
             'St. Lawrence',
             'Saigon',
             'Seine',
             'Tagus',
             'Thames',
             'Tiber',
             'Tigris',
             'Volga',
             'Yangtze',
             'Gulf of Aden',
             'Gulf of Mexico',
             'Gulf of Oman',
             'Alps',
             'Andes',
             'Appalachians',
             'Atlas Mountains',
             'Caucasus',
             'Himalayas',
             'Pyrenees',
             'Rockies',
             'Rocky Mountains',
             'Urals',
             'equator',
             'he equator',
             'Far East',
             'Gobi',
             'Gobi desert',
             'Kalahari',
             'Kalahari desert',
             'Middle East',
             'Near East',
             'North Pole',
             'Occident',
             'Orient',
             'Panama Canal',
             'Sahara',
             'Sahara desert',
             'South Pole',
             'Suez Canal',
             'Tropic of Cancer',
             'Tropic of Capricorn',
             'Association']